### ISSUE TITLE
Unity 5.5

### ISSUE THREAD

**Issue by Stevie-Ray** [nickjanssen/ThreeExporter#1]
Are you still working on support for Unity 5.5? 

Would love to see an update on this project! When I try to import your plugin i get the following error message:

> Assembly: 'Assets/Editor/ThreeExporter/ThreeExporter.dll' uses obsolete Unity API (UnityUpgradable)

The demo content you supplied works in my A.R. application, would like to make my own 3D classroom ;-)

Dankjwel alvast! 

Stevie

**Comment by jlieb10** [comment]
@nickjanssen Same question as @Stevie-Ray thanks!!

**Comment by nickjanssen** [comment]
@Stevie-Ray @jlieb10 My apologies for the delay.

Unfortunately, there is no support for Unity 5.5 at this point as there were some breaking changes to the lightmapping API. I looked into it but could not find an immediate solution. I don't have the time to look at this more thoroughly and it is unlikely that I will anytime soon due to my interests shifting away from Unity.

However, Unity 5.4 should work fine if you really need it. Perhaps you can export your scene from Unity 5.5, import it in 5.4 and use the plugin there instead?

**Comment by KooIaIa** [comment]
It looks like exporting scenes from 5.5 to 5.4 is pretty much impossible.

**Comment by nickjanssen** [comment]
@KooIaIa only the scenes? Would it be a lot of work for you to recreate these by starting a new project in 5.4?
